name: C++ CI

on: [push]

jobs:


  macOS:
  
    runs-on: macOS-latest
  
    steps: 
    - uses: actions/chckout@master
    - name: git submodule udate
      run: git submodule update --init --recursive
    - name: brew
      run: |
           brew cleanup
           brew doctor
           brew update
    - name: boost
      run: brew install boost@1.60
    - name: openssl
      run: brew install openssl 
    - name: autoconf
      run: brew install autoconf 
    - name: automake
      run: brew install automake
    - name: libtool
      run: brew install libtool
    - name: cmake
      run: |
           cmake -DCMAKE_BUILD_TYPE=Debug -DBOOST_ROOT=/usr/local/opt/boost@1.60 -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl ..
           make -j1 witness_node
           
