name: C++ CI

on: [push]

jobs:
  ubuntu:
  
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@master
    - name: configure
      run: sudo apt-get install --allow-unauthenticated libcurl4-openssl-dev libboost-thread-dev libboost-iostreams-dev libboost-date-time-dev libboost-system-dev libboost-filesystem-dev libboost-program-options-dev libboost-chrono-dev libboost-test-dev libboost-context-dev libboost-regex-dev libboost-coroutine-dev cmake parallel
    - name: "submodule update"
      run: git submodule update --init --recursive
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS=--coverage -DCMAKE_CXX_FLAGS=--coverage -DBoost_USE_STATIC_LIBS=OFF -DCMAKE_CXX_OUTPUT_EXTENSION_REPLACE=ON .
    - name: make
      run: make witness_node

  macOS:
  
    runs-on: macOS-latest
  
    steps:
    - uses: actions/checkout@master
    - name: wget xcode
      run: wget https://gist.github.com/mokagio/b974620ee8dcf5c0671f
    - name: install xcode
      run: sh b974620ee8dcf5c0671f
