name: C++ CI

on: [push]

jobs:


  macOS:
  
    runs-on: macOS-latest
  
    steps:
    - uses: actions/checkout@master
    - name: configure
      run: |
           wget -O install-xcode.sh https://gist.githubusercontent.com/mokagio/b974620ee8dcf5c0671f/raw/98c372acec9a7fc6c59b5f6660a5e12af7abcff5/install-xcode-cli-tools.sh
           sh install-xcode.sh
    - name: brew
      run: |
           brew cleanup
           brew doctor
           brew update
    - name: boost
      run: brew install boost@1.60
    - name: openssl
      run: brew install openssl 
    - name: autoconf
      run: brew install autoconf 
    - name: automake
      run: brew install automake
    - name: libtool
      run: brew install libtool
    - name: make
      run: |
           git submodule update --init --recursive
           cmake -DCMAKE_BUILD_TYPE=Debug -DBOOST_ROOT=/usr/local/opt/boost@1.60 -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl .
           make -j1 witness_node
           
