name: C++ CI

on: [push]

jobs:


  macOS:
  
    runs-on: macOS-latest
  
    steps: 
    - uses: actions/checkout@master
    - name: submodule udate
      run: git submodule update --init --recursive
    - name: brew
      run: |
           brew cleanup
           brew doctor
           brew update
    - name: boost
      run: brew install boost@1.60
    - name: openssl
      run: brew install openssl 
    - name: autoconf
      run: brew install autoconf 
    - name: automake
      run: brew install automake
    - name: libtool
      run: brew install libtool
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Debug -DBOOST_ROOT=/usr/local/opt/boost@1.60 -DCMAKE_C_FLAGS=--coverage -DCMAKE_CXX_FLAGS=--coverage -DBoost_USE_STATIC_LIBS=OFF -DCMAKE_CXX_OUTPUT_EXTENSION_REPLACE=ON .
    - name: make
      run: make witness_node
