name: C++ CI

on: [push]

jobs:

  ubuntu:
  
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@master
    - name: configure
      run: sudo apt-get install --allow-unauthenticated libcurl4-openssl-dev libboost-thread-dev libboost-iostreams-dev libboost-date-time-dev libboost-system-dev libboost-filesystem-dev libboost-program-options-dev libboost-chrono-dev libboost-test-dev libboost-context-dev libboost-regex-dev libboost-coroutine-dev cmake parallel
    - name: "submodule update"
      run: git submodule update --init --recursive
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS=--coverage -DCMAKE_CXX_FLAGS=--coverage -DBoost_USE_STATIC_LIBS=OFF -DCMAKE_CXX_OUTPUT_EXTENSION_REPLACE=ON .
    - name: make
      run: make cli_wallet

  macOS:
  
    runs-on: macOS-latest
  
    steps: 
    - uses: actions/checkout@master
    - name: brew
      run: |
           brew cleanup
           brew doctor
           brew update
    - name: gcc
      run: brew install gcc@7
    - name: boost
      run: brew install boost@1.60
    - name: openssl
      run: brew install openssl 
    - name: autoconf
      run: brew install autoconf 
    - name: automake
      run: brew install automake
    - name: libtool
      run: brew install libtool
    - name: submodule udate
      run: git submodule update --init --recursive
    - name: cmake
      run: cmake -DMAKE_CXX_COMPILER="g++-7 "-DCMAKE_C_COMPILER="gcc-7" -DCMAKE_BUILD_TYPE=Debug -DBOOST_ROOT=/usr/local/opt/boost@1.60 -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DCMAKE_C_FLAGS=--coverage -DCMAKE_CXX_FLAGS=--coverage -DBoost_USE_STATIC_LIBS=OFF -DCMAKE_CXX_OUTPUT_EXTENSION_REPLACE=ON .
    - name: make
      run: make witness_node
