name: Ubuntu

on: [push]

jobs:
  ubuntu:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
        branch: [secp256k1-zkp] # master, develop]
        boost_root: [/usr/include/boost, /usr/local/share/boost/1.69.0] # apt default, 1.69.0
        make: [all, witness_node, cli_wallet]
    runs-on: ${{ matrix.os }}
    steps:
    - name: configure
      run: |
           sudo apt update
           sudo apt-get install --allow-unauthenticated libcurl4-openssl-dev libboost-thread-dev libboost-iostreams-dev libboost-date-time-dev libboost-system-dev libboost-filesystem-dev libboost-program-options-dev libboost-chrono-dev libboost-test-dev libboost-context-dev libboost-regex-dev libboost-coroutine-dev cmake parallel
    - name: checkout
      run: |
           git clone https://github.com/ryanrfox/bitshares-core.git
           cd bitshares-core
           git checkout ${{ matrix.branch }}
           git submodule update --init --recursive
    - name: cmake
      run: |
           cd bitshares-core
           cmake -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=${{ matrix.boost_root }} .
    - name: make
      run: |
           cd bitshares-core
           make ${{ matrix.make }}
