name: C++ CI

on: [push]

jobs:


  windows:
  
    runs-on: windows-2016
    
    steps:
    - name: GitHub
      run: |
           git clone https://github.com/bitshares/bitshares-core.git
           cd bitshares-core
           git checkout release
           git submodule update --init --recursive
           cd
    - name: curl
      shell: powershell
      run: |
           cd d:\
           Import-Module BitsTransfer
           Start-BitsTransfer -Source https://curl.haxx.se/download/curl-7.65.3.zip -Destination curl.zip
           Expand-Archive '.\curl.zip' '.\' 
           $oldpath = (Get-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment' -Name PATH).path
           Write-Output $oldpath
           $newpath = "$oldpath d:\curl\curl-7.65.3;"
           Write-Output $newpath
           Set-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment' -Name PATH -Value $newpath
           Write-Output (Get-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment' -Name PATH).path
           
    - name: cmake
      run: |
           cd
           echo %PATH%
           echo %BOOST_ROOT_1_69_0%
           SET VS_VERSION="Visual Studio 15 2017 Win64"
           SET CURL_DIR="c:\Program Files\CURL"

           cmake -G %VS_VERSION% -A x64 -DCMAKE_CXX_FLAGS="--coverage" -DBOOST_ROOT="C:\Program Files\Boost\1.69.0" -DCURL_STATICLIB=ON -DCURL_LIBRARY=%CURL_DIR%\lib\libcurl_imp.lib -DCURL_INCLUDE_DIR=%CURL_DIR%\include -DOPENSSL_CONF_SOURCE="C:\Program Files\Common Files\SSL\openssl.cnf" ..
           rem cmake --build . --target install --conf
           cd
