name: C++ CI

on: [push]

jobs:

  windows-master:
  
    runs-on: windows-2016
    
    steps:
    - name: git
      run: |
           git clone https://github.com/bitshares/bitshares-core.git
           cd bitshares-core
           git checkout master
           git submodule update --init --recursive
    - name: curl
      shell: powershell
      run: |
           cd d:\
           Import-Module BitsTransfer
           Start-BitsTransfer -Source https://curl.haxx.se/download/curl-7.65.3.zip -Destination curl.zip
           Expand-Archive '.\curl.zip' '.\'
    - name: openssl
      shell: powershell
      run: |
           ### These are the paths containing openssl.conf
           # C:\hostedtoolcache\windows\Ruby\2.4.6\x64\msys64\usr\ssl
           # C:\hostedtoolcache\windows\Ruby\2.5.5\x64\msys64\usr\ssl
           # C:\hostedtoolcache\windows\Ruby\2.6.3\x64\msys64\usr\ssl
           # C:\Miniconda\Library
           # C:\Miniconda\pkgs\openssl-1.1.1b-he774522_1\Library
           # C:\Program Files\Common Files\SSL
           # C:\Program Files\Git\mingw64\ssl
           # C:\Program Files\Git\usr\ssl
           # C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\ssl
           # C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\usr\ssl
           # C:\tools\php\extras\ssl
           ### They were found using this and took about 30 minutes to execute
           # Get-ChildItem -Path C:\ -Include openssl.cnf -File -Recurse -ErrorAction SilentlyContinue
           # Get-ChildItem -Path D:\ -Include openssl.cnf -File -Recurse -ErrorAction SilentlyContinue
    - name: cmake
      run: |
           dir /s "C:\Miniconda\pkgs\openssl-1.1.1b-he774522_1"
           cd d:\a\bitshares-core\bitshares-core\bitshares-core
           SET VS_VERSION="Visual Studio 15 2017"
           SET CURL_DIR=d:\curl\curl-7.65.3
           SET OPENSSL_ROOT_DIR=C:\Miniconda\pkgs\openssl-1.1.1b-he774522_1\Library
           REM dir /s "C:\Program Files\OpenSSL"
           REM dir /s "C:\Program Files\Common Files\SSL"
           REM dir "C:\Program Files\Common Files"           
           REM SET LIBCRYPTO=%OPENSSL_ROOT_DIR%\libcrypto-1_1-x64.dll
           REM SET OPENSSL_CONF=C:\Program Files\Common Files\SSL\openssl.cnf
           SET PATH=%CURL_DIR%;%OPENSSL_ROOT_DIR%;%PATH%
           ECHO %PATH%
           cmake -G %VS_VERSION% -DOPENSSL_CONF_SOURCE="%OPENSSL_ROOT_DIR%\openssl.cnf" -DOPENSSL_ROOT="%OPENSSL_ROOT_DIR%" -DCURL_STATICLIB=ON -DCURL_LIBRARY="%CURL_DIR%\lib\libcurl_imp.lib" -DCURL_INCLUDE_DIR="%CURL_DIR%\include" -DBOOST_ROOT="%BOOST_ROOT%" -DCMAKE_GENERATOR_PLATFORM=x64  .
           REM -DOPENSSL_CRYPTO_LIBRARY="%OPENSSL_ROOT_DIR%" -DOPENSSL_LIBRARIES="%OPENSSL_ROOT_DIR%" -DOPENSSL_INCLUDE_DIR="%OPENSSL_ROOT_DIR%" 
           rem cmake --build . --target install --conf
