name: C++ CI

on: [push]

jobs:

  windows-master:
  
    runs-on: windows-2016
    
    steps:
    - name: git
      run: |
           git clone https://github.com/bitshares/bitshares-core.git
           cd bitshares-core
           git checkout master
           git submodule update --init --recursive
           cd
    - name: curl
      shell: powershell
      run: |
           cd d:\
           Import-Module BitsTransfer
           Start-BitsTransfer -Source https://curl.haxx.se/download/curl-7.65.3.zip -Destination curl.zip
           Expand-Archive '.\curl.zip' '.\'            
    - name: cmake
      run: |
           cd d:\a\bitshares-core\bitshares-core\bitshares-core
           SET VS_VERSION="Visual Studio 15 2017"
           ECHO %BOOST_ROOT%
           SET CURL_DIR=d:\curl\curl-7.65.3
           SET OPENSSL_ROOT_DIR=C:\Program Files\OpenSSL\bin
           SET LIBCRYPTO=%OPENSSL_ROOT_DIR%\libcrypto-1_1-x64.dll
           SET OPENSSL_CONF=C:\Program Files\Common Files\SSL\openssl.cnf
           SET PATH=%CURL_DIR%;%OPENSSL_ROOT_DIR%;%PATH%
           ECHO %PATH%
           ECHO %LIBCRYPTO%
           dir /s "C:\Program Files\OpenSSL"
           ECHO -G %VS_VERSION% -DCMAKE_GENERATOR_PLATFORM=x64 -DBOOST_ROOT="%BOOST_ROOT%" -DCURL_STATICLIB=ON -DCURL_LIBRARY="%CURL_DIR%\lib\libcurl_imp.lib" -DCURL_INCLUDE_DIR="%CURL_DIR%\include" -DOPENSSL_CONF_SOURCE="%OPENSSL_CONF%" -DOPENSSL_LIBRARIES="%LIBCRYPTO%" -DOPENSSL_ROOT_DIR="%OPENSSL_ROOT_DIR%" -DOPENSSL_ROOT="%OPENSSL_ROOT_DIR%" .
           cmake -G %VS_VERSION% -DCMAKE_GENERATOR_PLATFORM=x64 -DBOOST_ROOT="%BOOST_ROOT%" -DCURL_STATICLIB=ON -DCURL_LIBRARY="%CURL_DIR%\lib\libcurl_imp.lib" -DCURL_INCLUDE_DIR="%CURL_DIR%\include" -DOPENSSL_CONF_SOURCE="%OPENSSL_CONF%" -DOPENSSL_LIBRARIES="%LIBCRYPTO%" -DOPENSSL_ROOT_DIR="%OPENSSL_ROOT_DIR%" -DOPENSSL_ROOT="%OPENSSL_ROOT_DIR%" .
           rem cmake --build . --target install --conf
