name: C++ CI

on: [push]

jobs:

  windows-master:
  
    runs-on: windows-2016
    
    steps:
    - name: vcpkg
      run: |
           vcpkg search
           vcpkg --triplet x64-windows install zlib
           vcpkg --triplet x64-windows install curl
           REM vcpkg list
           REM dir /s %VCPKG_INSTALLATION_ROOT%
    - name: curl-download
      shell: powershell
      run: |
           cd d:\
           Import-Module BitsTransfer
           Start-BitsTransfer -Source https://curl.haxx.se/download/curl-7.65.3.zip -Destination curl.zip
           Expand-Archive '.\curl.zip' '.\'
    - name: curl-build
      run: |
           SET VS_VERSION="Visual Studio 15 2017"
           cd d:\
           git clone https://github.com/curl/curl
           cd curl
           git checkout tags/curl-7_64_1
           REM buildconf.bat
           mkdir curl-build
           cd curl-build
           cd
           REM cmake -G %VS_VERSION% -DCMAKE_GENERATOR_PLATFORM=x64 -DCMAKE_C_FLAGS=Werror -DCMAKE_USE_OPENSSL=ON -DCURL_DISABLE_FTP=ON -DCURL_DISABLE_LDAP=ON -DCURL_DISABLE_TELNET=ON -DCURL_DISABLE_DICT=ON -DCURL_DISABLE_FILE=ON -DCURL_DISABLE_TFTP=ON -DCURL_DISABLE_LDAPS=ON -DCURL_DISABLE_RTSP=ON -DCURL_DISABLE_POP3=ON -DCURL_DISABLE_IMAP=ON -DCURL_DISABLE_SMTP=ON -DCURL_DISABLE_GOPHER=ON -DCURL_STATICLIB=ON ..\
           REM cmake --build . --target install --config Release    
           cd
    - name: openssl
      shell: powershell
      run: |
           ### These are the paths containing openssl.conf
           # C:\hostedtoolcache\windows\Ruby\2.4.6\x64\msys64\usr\ssl
           # C:\hostedtoolcache\windows\Ruby\2.5.5\x64\msys64\usr\ssl
           # C:\hostedtoolcache\windows\Ruby\2.6.3\x64\msys64\usr\ssl
           # C:\Miniconda\Library
           # C:\Miniconda\pkgs\openssl-1.1.1b-he774522_1\Library
           # C:\Program Files\Common Files\SSL
           # C:\Program Files\Git\mingw64\ssl
           # C:\Program Files\Git\usr\ssl
           # C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\ssl
           # C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\usr\ssl
           # C:\tools\php\extras\ssl
           ### They were found using this and took about 30 minutes to execute
           # Get-ChildItem -Path C:\ -Include openssl.cnf -File -Recurse -ErrorAction SilentlyContinue
           # Get-ChildItem -Path D:\ -Include openssl.cnf -File -Recurse -ErrorAction SilentlyContinue
    - name: bitshares
      run: |
           cd d:\
           SET VS_VERSION="Visual Studio 15 2017"
           REM SET CURL_ROOT_DIR=d:\curl\curl-7.65.3
           SET CURL_ROOT_DIR=C:\vcpkg\packages\curl_x64-windows
           dir /s "%CURL_ROOT_DIR%"
           SET OPENSSL_ROOT_DIR=C:\Miniconda\pkgs\openssl-1.1.1b-he774522_1\Library
           SET ZLIB_ROOT=C:\vcpkg\packages\zlib_x64-windows
           SET PATH=%CURL_ROOT_DIR%;%OPENSSL_ROOT_DIR%;%LIB_ROOT%;%PATH%
           ECHO %PATH%
           git clone https://github.com/bitshares/bitshares-core.git
           cd bitshares-core
           git checkout master
           git submodule update --init --recursive
           cmake -G %VS_VERSION% -DCURL_STATICLIB=ON -DCURL_LIBRARY="%CURL_ROOT_DIR%\lib\libcurl.lib" -DCURL_INCLUDE_DIR="%CURL_ROOT_DIR%\include\curl" -DBOOST_ROOT="%BOOST_ROOT%" -DCMAKE_GENERATOR_PLATFORM=x64 .
    - name: make
      run: |
           cd d:\bitshares-core
           cmake --build . --target install --config Release
           
